---
engines:
  duplication:
    enabled: false
  eslint:
    enabled: true
    channel: stable
    config:
      config: .eslintrc
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**/*.js"
exclude_paths: []
